name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '44 1 * * *'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: gradle/wrapper-validation-action@v1
    - name: gradle cache 
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle and publish to Maven Local
      run: ./gradlew pTML
    - name: Upload package
      uses: actions/upload-artifact@v1
      with:
        name: guppy-${{github.run_number}}-distribution
        path: ~/.m2/repository/com/github/marco-schmidt/guppy/
